services:
  # Backend API service for development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sample-api-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      # Mount source code for development
      - ./backend:/app:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - sample-api-network

  # Frontend development service
  frontend-dev:
    image: node:18-alpine
    container_name: sample-api-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sample-api-network

# Create a custom network for service communication
networks:
  sample-api-network:
    driver: bridge