name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build backend Docker image (verifies compilation)
      - name: Build backend Docker image
        working-directory: ./backend
        run: docker build -t sample-api-backend .

      # Build frontend Docker image (verifies compilation)
      - name: Build frontend Docker image
        working-directory: ./frontend
        run: docker build -t sample-api-frontend .

      # Backend linting
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Run backend linting
        working-directory: ./backend
        run: |
          uv run black --check .
          uv run isort --check-only .
          uv run flake8 src/ app.py cli.py
          uv run mypy src/

      # Frontend linting
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run frontend linting
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint

      # Run backend unit tests
      - name: Run backend unit tests
        working-directory: ./backend
        run: |
          uv run python -m unittest discover -s tests/unit -p 'test_*.py' -v

